---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  encryptedData:
    api_key: AgCO18rYYykyZVA0q03tTr9fsc1NA2zDsZNAGhLfdu9yjyQe6ZnCcuRGg3/xxCSN7YjITabqg9G0skJj8DUgoztoqyAfqAgTbjGYL2Q1C40vziMw6IGSO42c3RH8jeqTuDIAyDL04SFTBsR6hd4PRjdZyAFmnmqlQTK0+3jV9MhHg6skgQo1zYUEKEbiRlvbClHHZ033/5YKE7ExumAYJPkdhi7+bxIw2ZAZttLgU82KomQ3ewd8WNsRy2gUr/azoRi/6rNy5QTkbDWOyb0FvpFiQr8GsaCCFJFUDkk77f7YGL1gMBgIGZCSCR0Ix/G+yqYFsmzIU/W28X5M/9XkcoHgTOhc3hgtGpYDnZ9ONlgzQhjDJ2cvpq/aZcLPozE3sZDhRTYbwT20HDq+1KYFPuVhaO7NaJ7x52a8DjQMp+kChRnot4IOxLhj1eDgVicffAD4k2HPmWO6gi45yvatNfaImMif3DflcbbI9wb/quTnoFT1vEcVdeeJ7Abg011Dn4qZpa9yxoWnd+BpwOZZ/Y4kQiAOx/FlgCX+ghn2WV+6BIMfgOPH/lMXkEJpHr1tD5bIjrMlw2s7VBrT3KGD0c8zDQNiYedISBFfTTjVLR2Sem+G/RLNvDAeQNn4k7Rw5KSKSEBg7QhmSQi/fgQKy36SWyypIYNovH+gNqkKxNG5PzcFytaZ0x7WCfwognH0P4pa5vTiey+iyWBFP4g0i33+IOY=
  template:
    metadata:
      name: {{ .Release.Name }}-secret
      namespace: {{ .Release.Namespace }}
