{{- if .Values.sealedSecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  encryptedData:
    api_key: {{ .Values.sealedSecret.encryptedApiKey }}
  template:
    metadata:
      name: {{ .Release.Name }}-secret
      namespace: {{ .Release.Namespace }}
{{- end }}
