apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stable-service
  labels:
    app: {{ .Release.Name }}
    service: stable
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
