# Default values for k8s-nodejs-app.
replicaCount: 2

image:
  repository: leejay5914/k8s-nodejs-app
  pullPolicy: IfNotPresent
  tag: "06171f9cb33b403b2d2a906ac990a4adcbd7a80e"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}
tolerations: []
affinity: {}
