# Default values for k8s-nodejs-app.
replicaCount: 2

image:
  repository: leejay5914/k8s-nodejs-app
  pullPolicy: IfNotPresent
  tag: "5ae1b59ac61921a478b0035ddd991382526f4413"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true 
  className: ""
  annotations: {}
  hosts:
    - host: my-k8s-app.com
      paths:
        - path: /api 
          pathType: Prefix 
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}
tolerations: []
affinity: {}
