# Default values for k8s-nodejs-app.
replicaCount: 2

image:
  repository: leejay5914/k8s-nodejs-app
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: NodePort
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}
tolerations: []
affinity: {}
