# Default values for k8s-nodejs-app.
replicaCount: 2

image:
  repository: leejay5914/k8s-nodejs-app
  pullPolicy: IfNotPresent
  tag: "5ae1b59ac61921a478b0035ddd991382526f4413"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

# Pod 보안 컨텍스트
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

# 컨테이너 보안 컨텍스트
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Node.js - /tmp 쓰기 필요할 수 있음
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  className: ""
  annotations: {}
  hosts:
    - host: my-k8s-app.com
      paths:
        - path: /api 
          pathType: Prefix 
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready # 별도의 readiness 체크
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

startupProbe:      
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30  # 최대 5분 대기

nodeSelector: {}
tolerations: []
affinity: {}

# Analysis 설정
analysis:
  successRateThreshold: 0.05  # 5xx 오류율 임계값 (5%)
  interval: 5m
  timeout: 10m