# Staging Environment Values
# 개발/테스트 환경용 설정 - 리소스 축소, 외부 접근 차단

replicaCount: 2

image:
  repository: leejay5914/k8s-nodejs-app
  pullPolicy: IfNotPresent
  tag: "5ae1b59ac61921a478b0035ddd991382526f4413"

# Staging은 외부 접근 차단 (kubectl port-forward로 접근)
ingress:
  enabled: false

# 리소스 축소 (개발/테스트 환경)
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Health check는 동일하게 유지
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

# Analysis 설정 (Canary 배포용)
analysis:
  successRateThreshold: 0.05
  interval: 5m
  timeout: 10m
