apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-nodejs-app-secrets
  namespace: argocd
  annotations:
    # Secret은 앱보다 먼저 배포
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/squatboy/k8s-nodejs-app-manifests.git
    targetRevision: HEAD
    path: apps/workloads/secrets
    plugin:
      name: sops 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
