apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-nodejs-app
  namespace: argocd
  annotations:
    # --- Sync Wave ---
    argocd.argoproj.io/sync-wave: "2"
    # --- Image Updater ---
    argocd-image-updater.argoproj.io/image-list: my-image=leejay5914/k8s-nodejs-app
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
    argocd-image-updater.argoproj.io/my-image.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/my-image.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/squatboy/k8s-nodejs-app-manifests.git
    targetRevision: HEAD
    path: .
    plugin:
      name: sops
      env:
        - name: HELM_ENABLED
          value: "true"
        - name: HELM_CHART_PATH
          value: "charts/k8s-nodejs-app"
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
