# apps/root.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  # ArgoCD가 자기 자신을 관리하게 함 (선택적이지만 권장)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/squatboy/k8s-app-manifests.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # 루트 앱 자체는 argocd 네임스페이스에
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
